CREATE DATABASE DM_Vet30;
USE DM_Vet30;

CREATE TABLE Owner
( id INT(10) NOT NULL AUTO_INCREMENT,
firstname VARCHAR(20) NOT NULL,
lastname VARCHAR(20) NOT NULL,
email VARCHAR(20),
PRIMARY KEY(id)
);

CREATE TABLE Pet
( id INT(10) NOT NULL AUTO_INCREMENT,
name VARCHAR(20) NOT NULL,
species VARCHAR(20) NOT NULL,
weight INT(20),
birthdate Date,
ownerid INT(10),
PRIMARY KEY(id),
FOREIGN KEY(ownerid) REFERENCES Owner(id) ON DELETE SET NULL ON UPDATE CASCADE
);